# Generated by Django 4.2.28 on 2026-02-16 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When blog was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When blog was submitted for review', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When comment was moderated', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Moderator who reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
